openapi: 3.1.0
info:
  version: 1.0.0
  title: Contacts API
  description: API documentation for the Contacts application. Manage user contacts and authentication, including endpoints for creating, retrieving, updating, and deleting contacts.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
tags:
  - name: Contacts
    description: "Manage user contacts: create, retrieve, update, and delete."
  - name: Auth
    description: Authentication and token management endpoints.
servers:
  - url: http://localhost:3000
  - url: https://nodejs-hw-mongodb-0qq7.onrender.com
paths:
  /contacts:
    get:
      $ref: ../swagger/paths/contacts/get.yaml
    post:
      $ref: ../swagger/paths/contacts/post.yaml
  /contacts/{contactId}:
    get:
      $ref: ../swagger/paths/contacts/{id}/get.yaml
    patch:
      $ref: ../swagger/paths/contacts/patch.yaml
    delete:
      $ref: ../swagger/paths/contacts/delete.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
